name: Generate Custom Contribution Graph

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch Data and Generate SVG Graph
        env:
          GRAPH_TOKEN: ${{ secrets.GRAPH_TOKEN }}
        run: node generate-graph.js

      - name: Commit and Push Generated Image
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add activity-graph.svg
          git commit -m "Automated update of activity graph" || exit 0
          git push
